name: Build Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Build for ARM
        env:
          GOOS: linux
          GOARCH: arm64
        run: |
          vers="1.${{ github.run_number }}"
          go build -ldflags "-w -s" -o "gowget-$(vers)" main.go
          upx --brute "gowget-$(vers)"
          sha256sum "gowget-$(vers)" > gowget-$(vers).sha256

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            "gowget-1.${{ github.run_number }}"
            "gowget-1.${{ github.run_number }}.sha256"
          tag_name: 1.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
