name: Build Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Build for ARM
        env:
          GOOS: linux
          GOARCH: arm64
        run: |
          go build -ldflags "-w -s" -o gowget main.go
          upx --brute gowget
          sha256sum gowget > gowget.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            gowget
            gowget.sha256
          tag_name: release-${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
